### ISSUE TITLE
The description of attributions.json of n5 dataset

### ISSUE THREAD

**Issue by visaVita** [saalfeldlab/CNNectome#17]
I would like to ask what is the meaning of 'offset' and 'resolution' in attributes.json of ground truth, because offset has far exceeded the dimension of s0 in raw data.

![WechatIMG1412](https://github.com/saalfeldlab/CNNectome/assets/30430928/bb80969b-509c-4882-94d0-b856a8107a6e)

**Comment by neptunes5thmoon** [comment]
the offset attribute indicates the position of the crop in the raw EM data and as indicated by "offset_unit" it is given in nm.

For the crop in your screenshot the size of the raw data (jrc_hela-3) in nm is (12400, 1000, 12000) * (4,4,4) = (49600, 4000, 48000).

Hope that helps!
