### ISSUE TITLE
Some puzzles about the data 

### ISSUE THREAD

**Issue by artzjj** [saalfeldlab/CNNectome#2]
data "volumes/masks/groundtruth" in Line 29  in CNNectome/training/isotropic/train_dist.py can not be found in cremi dataset downloaded from [https://cremi.org/data/](url). And how can I get the data used in your code?
Thanks!

**Comment by neptunes5thmoon** [comment]
You can see how I generated `volumes/masks/groundtruth` in `utils/rewrite_mask.py`. It is a mask for where groundtruth annotations exist, which is helpful for working with realigned data.
