### ISSUE TITLE
Issue with BOOST_SRC

### ISSUE THREAD

**Issue by jcs0902** [saalfeldlab/CNNectome#5]
While trying to get CNNectome to run on my labs AWS instance, I ran into an error that crashes the docker build command while trying to compile the docker image so that we can push this image to AWS. The issue seems to be that the link to Boost is not correct, but I went to their website and tried to just update the version and it is still not working. Any suggestions would be great!

ERROR: executor failed running [/bin/sh -c wget ${BOOST_SRC} -O ${BOOST_TAR}]: exit code: 8

**Comment by neptunes5thmoon** [comment]
Hi @jcs0902!

Updates to the repo were happening on a separate branch (v2.0), your error looks like you were using master. I have now pushed all updates to master, so you could retry building it from there.

Additionally, you can also get the docker image directly from [this dockerhub](https://hub.docker.com/repository/docker/neptunes5thmoon/cnnectome/general).

Let me know if you run into more problems!

Best,
Larissa

**Comment by neptunes5thmoon** [comment]
Gonna close this. Feel free to make a new issue if you run into additional problems!
